# -*- coding: utf-8 -*-
"""Cellular Network Data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/eligabaldon/cellular-network-data-analysis.82bfde8a-61cb-48b7-bc3f-ddf024b07b8d.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260627/auto/storage/goog4_request%26X-Goog-Date%3D20260627T015145Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D213b98ac425bfbdcf1bf7300652657ace95002f739cd588f5b3859eead3edc3a35fdd42cea6319fbe4933b12a06904f1986b5e83f4de699b7a81bff1383f0d6587c2f1396c0b7ee7a37cd195a0a9459a5019be7b5c29e061d2115f85b6052fd46ee2c40d4fcb0c93730167c154a9427a679cadf9a73ad103b3eddba4f9396dd75a42d1546e3a7ef511365edfa0d9d41d527a4d7f3715ab64b1a8ed72722cfd35dc1191facd7b4773127bbb6c538ce561c3c7ff949771e42df66b89f8e747a3b70b04a83cb89c89a187b9f39394f0b2b386c6c19d0c5834a7f9a8b6f39f1f820f9e402e94147b6dd9996872a4b66b64b865b8aa4204033ca94df5696e9c53764c
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
suraj520_cellular_network_analysis_dataset_path = kagglehub.dataset_download('suraj520/cellular-network-analysis-dataset')

print('Data source import complete.')

"""# CELLULAR DATA ANALYSIS"""

import pandas as pd
df=pd.read_csv(r'/kaggle/input/cellular-network-analysis-dataset/signal_metrics.csv')

df.head()

df.columns

"""# Getting to know the data"""

df.shape

df.dtypes

df['Timestamp'] = pd.to_datetime(df['Timestamp'])

"""**FINDINGS:**

The dataset has 16829 rows of records and 12 columns as expected.

The timestamp values were imported as strings, and they were changed to datetime.

## Column 1: Timestamp
"""

#checking for missing values
df["Timestamp"].isna().sum()

print("Earliest timestamp registered in the dataset is:", df["Timestamp"].min())
print("Latest timestamp registered in the dataset is:", df["Timestamp"].max())

print("Range of time is:", df["Timestamp"].max()-df["Timestamp"].min())

"""#### **Comments:**

1. No missing values in the timestamp column.

2. The range of time registered in this dataset is 36 days and 11 hours.

## Column 2: Locality

In this column, it is expected to have 20 regions in Bihar.
"""

#Value counts of the locality column
df["Locality"].value_counts()

#checking for any missing values in this column
df["Locality"].isna().sum()

import matplotlib.pyplot as plt

region_counts = df["Locality"].value_counts()

plt.figure(figsize=(20, 6))
plt.bar(region_counts.index, region_counts.values, color="#4FC0D0")
plt.xticks(region_counts.index, rotation=70)
plt.title("Locality Frequency")

plt.show()

"""#### **Comments:**

1. No missing values in the Locality column.

2. The 20 regions in Bihar are represented.

3. The most represented region is "Fraser Road".

4. The least represented region is "Anandpuri".

5. Investigation was done on "Boring Road" and "Boring Canal Road" to check if these refer to the same region. However, both regions turned out to be different so they were not merged.

6. All regions are considered evenly represented with a difference of 102 frequency points between the least represented region (frequency 799) and the most represented region (897).

## Columns 3&4: Latitude and Longitude
"""

df.head()

print("Number of missing values in latitude column is:",df["Latitude"].isna().sum())
print("Number of missing values in longitude column is:", df["Longitude"].isna().sum())

fig, axes = plt.subplots(1, 2, figsize=(25, 10))

axes[0].hist(df["Longitude"], bins=20, color="#164B60")
axes[0].set_title("Longitude")

axes[1].hist(df["Latitude"], bins=20, color="#FF8989")
axes[1].set_title("Latitude")

plt.suptitle("Longitude and Latitude Distribution Values")
plt.show()

print('Min Longitude:', df["Longitude"].min())
print('Max Longitude:', df["Longitude"].max())
print('Min Latitude:', df["Latitude"].min())
print('Max Latitude:', df["Latitude"].max())

"""#### **Comments:**

1. No missing values in both Longitude and Latitude columns.

2. The longitude and latitude values lie in the ranges for Bihar region. After checking, both values are valid for Bihar regions and are included within the Bihar latitude and longitude ranges.

3. No abnormal or outlier values were detected within these 2 columns.

## Column 5: Signal Strength (dBm)
"""

df.head()

print("Number of missing values in the signal strength column:", df["Signal Strength (dBm)"].isna().sum())

print("Minimum Signal Strength:",df["Signal Strength (dBm)"].min())
print("Maximum Signal Strength:", df["Signal Strength (dBm)"].max())
print("Mean Signal Strength:", df["Signal Strength (dBm)"].mean())

plt.figure(figsize=(15,15))
plt.hist(df["Signal Strength (dBm)"], bins=50, color="#8EAC50")
plt.xlabel("Signal Strength in dBm")
plt.ylabel("Frequency")
plt.title("Distribution of Signal Strength (dBm) across the dataset")
plt.show()

"""## Column 6: Signal Quality"""

df.head()

df["Signal Quality (%)"].value_counts()

df.drop(columns="Signal Quality (%)", inplace=True)

"""#### **Comments:**

1. This column was dropped as it does not hold significant information. All rows contain the value "0".

## Column 7: Data Throughput (Mbps)
"""

df["Data Throughput (Mbps)"].isna().sum()

print("The minimum recorded data throughput is:", df["Data Throughput (Mbps)"].min())
print("The maximum recorded data throughput is:", df["Data Throughput (Mbps)"].max())
print("The mean data throughput recorded is:", df["Data Throughput (Mbps)"].mean())
print("The range of data throughputs recorded is:", df["Data Throughput (Mbps)"].max()-df["Data Throughput (Mbps)"].min())

plt.figure(figsize=(5,5))
plt.hist(df["Data Throughput (Mbps)"], bins=50, color="#8EACC0")
plt.xlabel("Data Throughput (Mbps)")
plt.ylabel("Frequency")
plt.title("Distribution of Data Throughputs recorded across the dataset")
plt.show()

"""#### **Comments:**

1. No missing values in this column of the dataset.

2. The minimum data throughput recorded is 1 Mbps and the highest data throughput recorded is 99.98 Mbps.

3. No abnormal data was recorded in this column.

4. Lower data throughputs are the most frequent in the dataset. Likewise, the higher the data throughput, the lower the frequency in this dataset.

## Column 8: Latency (ms)
"""

df["Latency (ms)"].isna().sum()

print("The maximum latency recorded is:", df["Latency (ms)"].max())
print("The minimum latency recorded is:", df["Latency (ms)"].min())
print("The mean latency recorded is:", df["Latency (ms)"].mean())
print("The range of the latency is:", df["Latency (ms)"].max()-df["Latency (ms)"].min())

plt.figure(figsize=(10,3))
plt.hist(df["Latency (ms)"], bins=50, color="#F24C3D")
plt.xlabel("Latency (ms)")
plt.ylabel("Frequency")
plt.title("Distribution of Latencies recorded across the dataset")
plt.show()

"""#### **Comments:**

1. No missing values in this column of the dataset.

2. The minimum latency is 10 ms and the highest latency is 200 ms.

3. The mean latency is 101.3 ms and the range of latencies is 189 ms.

4. The majority of the latencies are equally represented, where no specific latency or range of latencies is overly expressed.

## Column 9: Network Type
"""

df["Network Type"].isna().sum()

network_types=df["Network Type"].value_counts()
network_types

import plotly.express as px
fig = px.pie(df, values=network_types.values, names=network_types.index)
fig.update_layout(
    width=400,
    height=400,
    margin=dict(l=0, r=0, t=0, b=0),
    plot_bgcolor="#ffffff",
    paper_bgcolor="#ffffff" )
plt.show(fig)
fig

"""#### **Comments:**

1. No missing values in this column of the dataset.

2. The 4 network types (3g, 4g, 5g, and LTE) are equally represented as per the pie chart.

## Column 10,11,12: BB60C, srsRAN, BladeRFxA9 Measurement

BB60C is a real-time spectrum analyzer and RF recorder. It can measure signals from 9 kHz to 6 GHz.
"""

df["BB60C Measurement (dBm)"].isna().sum()

print("Maximum measurement of BB6OC:", df["BB60C Measurement (dBm)"].max())
print("Minimum measurement of BB60C:", df["BB60C Measurement (dBm)"].min())

df.head()

df["srsRAN Measurement (dBm)"].isna().sum()

df["BladeRFxA9 Measurement (dBm)"].isna().sum()

"""# ANALYSIS"""

fig = px.scatter(df, x=df["Network Type"], y=df["Data Throughput (Mbps)"], color="Network Type", title="Data Throughput per Network Type")
plt.show(fig)
fig

fig = px.scatter(df, x=df["Locality"], y=df["Network Type"], color=df["Locality"], title="Network type representation per Locality")
plt.show(fig)
fig

fig = px.scatter(df, x=df["Network Type"], y=df["Latency (ms)"], color="Network Type", title="Latencies per Network Type")
plt.show(fig)
fig

fig = px.scatter(df, x="Data Throughput (Mbps)", y="Latency (ms)", title="Data Throughput vs Latency")
plt.show(fig)
fig

#BB60C Measurements
df["Difference BB60C"] = df["Signal Strength (dBm)"] - df["BB60C Measurement (dBm)"]
fig = px.histogram(df, x=df["Difference BB60C"],nbins=1000, title="Difference between Signal Strength and BB60C Measurement")
plt.show(fig)
fig

#srsRAN Measurements
df["Difference srsRAN"] = df["Signal Strength (dBm)"] - df["srsRAN Measurement (dBm)"]
fig = px.histogram(df, x=df["Difference srsRAN"],nbins=1000, title="Difference between Signal Strength and srsRAN Measurement")
plt.show(fig)
fig

#BladeRFxA9 Measurements
df["Difference BladeRFxA9"] = df["Signal Strength (dBm)"] - df["BladeRFxA9 Measurement (dBm)"]
fig = px.histogram(df, x=df["Difference BladeRFxA9"],nbins=1000, title="Difference between Signal Strength and BladeRFxA9 Measurement")
plt.show(fig)
fig

import numpy as np
#correlation between signal strength and BB60C measured signal strength
correlation_BB60C = np.corrcoef(df["Signal Strength (dBm)"], df["BB60C Measurement (dBm)"])[0, 1]
print('BB60C Measurement Correlation:',correlation_BB60C)

#correlation between signal strength and srsRAN measured signal strength
correlation_srsRAN = np.corrcoef(df["Signal Strength (dBm)"], df["srsRAN Measurement (dBm)"])[0, 1]
print('srsRAN Measurement Correlation:',correlation_srsRAN)

#correlation between signal strength and BladeRFxA9 measured signal strength
correlation_BladeRFxA9 = np.corrcoef(df["Signal Strength (dBm)"], df["BladeRFxA9 Measurement (dBm)"])[0, 1]
print('BladeRFxA9 Measurement Correlation:',correlation_BladeRFxA9)

fig = px.bar(x=[correlation_BB60C,correlation_BladeRFxA9,correlation_srsRAN], y=['BB60C','BladeRFxA9','srsRAN'], color=['BB60C','BladeRFxA9','srsRAN'], title="Correlations")
plt.show(fig)
fig

#RMSE for each device
for device in ["BB60C Measurement (dBm)", "srsRAN Measurement (dBm)", "BladeRFxA9 Measurement (dBm)"]:
    rmse = np.sqrt(np.mean(((df["Signal Strength (dBm)"] - df[device])**2)))
    print(f"RMSE for {device}: {rmse}")

# splitting the DataFrame based on network type
df_3g = df[df["Network Type"] == "3G"]
df_4g = df[df["Network Type"] == "4G"]
df_lte = df[df["Network Type"] == "LTE"]
df_5g = df[df["Network Type"] == "5G"]

#RMSE for each device in 3G
for device in ["BB60C Measurement (dBm)", "srsRAN Measurement (dBm)", "BladeRFxA9 Measurement (dBm)"]:
    rmse = np.sqrt(np.mean(((df_3g["Signal Strength (dBm)"] - df_3g[device])**2)))
    print(f"RMSE for {device}: {rmse}")

#RMSE for each device in 4G
for device in ["BB60C Measurement (dBm)", "srsRAN Measurement (dBm)", "BladeRFxA9 Measurement (dBm)"]:
    rmse = np.sqrt(np.mean(((df_4g["Signal Strength (dBm)"] - df_4g[device])**2)))
    print(f"RMSE for {device}: {rmse}")

#RMSE for each device in LTE
for device in ["BB60C Measurement (dBm)", "srsRAN Measurement (dBm)", "BladeRFxA9 Measurement (dBm)"]:
    rmse = np.sqrt(np.mean(((df_lte["Signal Strength (dBm)"] - df_lte[device])**2)))
    print(f"RMSE for {device}: {rmse}")

#RMSE for each device in 5G
for device in ["BB60C Measurement (dBm)", "srsRAN Measurement (dBm)", "BladeRFxA9 Measurement (dBm)"]:
    rmse = np.sqrt(np.mean(((df_5g["Signal Strength (dBm)"] - df_5g[device])**2)))
    print(f"RMSE for {device}: {rmse}")

rmse_df=pd.read_csv(r'/kaggle/input/rmse-values/RMSE.csv', header=1)

rmse_df.head()

rmse_df.drop(columns=['Unnamed: 5', 'Unnamed: 6'], inplace=True)

rmse_df.rename(columns={'Unnamed: 0':'Device'}, inplace=True)

rmse_df.head()

fig = px.histogram(rmse_df, x="Device", y=["RMSE 3G", "RMSE 4G", "RMSE LTE", "RMSE 5G"], barmode="group")

fig.show()

"""# FINAL FINDINGS AND ANALYSIS

Upon this extensive analysis, the following findings were concluded:

1. The dataset contains a total of 16829 rows (Records) and 12 columns.
2. The timestamp column data type was incorrect and was casted to datetime for consistency.
3. No missing values were found in all the columns.
4. 20 regions in Bihar were all almost equally represented, with Fraser Road as the most represented locality and Anandpuri as the least represented with a low general difference in representation counts between both.
5. Longitude and Latitude values are correct and consistent with the longitude and latitude ranges of Bihar.
6. Signal Quality column was dropped as it had no data and all rows contained 0.
7. Lower data throughputs are highly represented, which is consistent with the network types involved, especially with 3G and LTE.
8. The 4 network types are all almost equally represented (almost 25% each).
9. Each locality was tested for all network types.
10. Higher latencies were associated with 3G and LTE, and lower latencies are associated with 4G and 5G, which is consistent with the nature of these network types. No abnormal findings were found, for instance, no low latency was found for 3G and no high latency was found for 5G.
11. When subtracting the measured signal for the 3 devices and the original signal, there was a high concentration around 0 (indicating accuracy of measurement) and a bell-shaped distribution far from 0, which is consistent with the added noise.
12. BladeRFxA9 measurements showed a high correlation with the original signal, indicating high measurement accuracy.
13. RMSE calculations were done: Blade's RMSE was the lowest, followed by BB60C, then srsRAN: this indicates that Blade showed the least error in measuring the original signal, supporting point 12.
14. The dataset was split based on the network type. 4 sub-datasets were obtained (3G, LTE, 4G, 5G), to analyze the data for each network type individually.
15. In 3G: RMSE is equal for all 3 devices, meaning the 3 devices showed almost the same amount of measurement error and performed the same.
16. In LTE: Blade's RMSE was the lowest, followed by BB60C, then srsRAN, meaning Blade was the best performer in measuring LTE signals.
17. In 4G: Blade's RMSE was the lowest, followed by BB60C, then srsRAN, meaning Blade was the best performer in measuring 4G signals.
18. In 5G: Blade's RMSE was the lowest, followed by BB60C, then srsRAN, meaning Blade was the best performer in measuring 5G signals.
19. BB60C performs better in measuring 4G, LTE, and 5G signals than 3G signals, however, it behaved equally in 4G, LTE and 5G.
20. srsRAN behaves better in measuring signals as the frequency tends to increase, but still behaves less than all other measurement devices in this study.
21. Blade behaves better in measuring signals as the frequency tends to increase but shows a drastic decrease in measurement error as we shift from 3G to superior network types.
22. Blade is more reliable in measuring signals regardless of the network type when compared to the other measurement devices in this study, hence, supporting point 12. Moreover, BB60C follows as being the second best measurement device, then followed by srsRAN.
"""